# appveyor.yml

# Gunakan virtual machine Windows dengan Visual Studio 2022
image: Visual Studio 2022

# Tentukan versi Node.js LTS yang stabil
stack: node 20

# Atur cache untuk mempercepat proses build di kemudian hari
cache:
  - node_modules

# Perintah untuk menginstal semua dependensi
install:
  - npm install

# Nonaktifkan proses build default dari AppVeyor
build: off

# Perintah untuk menjalankan proses build aplikasi
build_script:
  # Menjalankan skrip "dist" yang ada di package.json
  - npm run dist

# Definisikan file hasil build (artefak) yang ingin disimpan dan bisa diunduh
artifacts:
  # Ambil file installer .exe yang dihasilkan oleh electron-builder di dalam folder dist
  - path: 'dist/*.exe'
    name: UjianBrowserInstaller